%% 根据map表，打印对应图形
plot( map(:,1),map(:,2),map(:,1),map(:,3),map(:,1),map(:,4) )
hold on;
plot( 1:length(map(:,1)) , 16*ones(1,length(map(:,1))) ,...
    'Color', 'k' ,...
    'LineStyle','-.' ) 
plot( 1:length(map(:,1)) , 85*ones(1,length(map(:,1))) ,...
    'Color', 'k' ,...
    'LineStyle','-.') 
xlabel({'重物球的质量  /m'},'FontSize',14);
ylabel({'α /°'},'FontSize',14);